# KRY project 1 - Affine cipher
# Timotej Ponek, xponek00

CC = g++
CFLAGS = -std=c++17 -Wall -Wunused -pedantic
PROJ = kry

CPP = main.cpp args.cpp kry.cpp

all:
	$(CC) $(CFLAGS) -o $(PROJ) $(CPP)

clean:
	rm -f *.o $(PROJ)