# BMS project 1 - LDPC coder
# Timotej Ponek, xponek00

CC = g++
CFLAGS = -std=c++17 -Wall -Wunused -pedantic
PROJ = bms

CPP = main.cpp args.cpp matrixOperations.cpp bms.cpp

all:
	$(CC) $(CFLAGS) -o $(PROJ) $(CPP)

clean:
	rm -f *.o bms matica.csv
